name: Assign New Issues on Open

on:
  issues:
    types: [opened]

jobs:
  assign_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Issue
        uses: peter-evans/assign-issue@v3.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          assignees: "Kronera"
